#!/usr/bin/env ansible-playbook
---
- name: provision sandbox
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./vars/ec2.yml 
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         volumes:
           - device_name: /dev/xvda
             volume_type: gp2
             volume_size: 20
           - device_name: /dev/sdb
             ephemeral: ephemeral0

         region: "{{ region }}"
         vpc_subnet_id: subnet-3cfe6d59
         assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: utility
        ansible_user: ec2-user
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
