#!/usr/bin/env ansible-playbook
---
- block:
  - name: install required packages
    yum: name={{ item }} state=installed
    with_items:
      - curl
      - openssl
      - unzip
      - tar
      - wget
      - java-1.8.0-openjdk
      - firewalld
      - ntp
      - nscd
      - wget
      - telnet
      - python-devel
      - gcc
      - bind-utils
      - krb5-workstation
      - krb5-libs

  - name: install mysql connector
    yum: name=mysql-connector-java state=installed
    when: hadoop_db == 'MySQL'
      
  when: ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  tags: packages

- block:
  - name: install epel
    yum_repository:
      name: epel
      description: EPEL YUM repo
      mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
      gpgkey: https://mirror.netcologne.de/fedora-epel//RPM-GPG-KEY-EPEL-7
      gpgcheck: yes
      failovermethod: priority

  - name: install python-pip
    yum: name=python-pip state=installed

  - name: upgrade pip
    pip: name=pip state=latest

  when: install_epel == True and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and ansible_distribution_major_version == '7'

- name: set hostname
  hostname: name={{ ansible_fqdn }}

- name: pause for a minute
  pause: minutes=1

- name: build hosts file
  lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' state=present line="{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_fqdn }}" #"
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: '{{ play_hosts }}'

- name: disable iptables
  service: name=firewalld state=stopped enabled=no

- name: disable selinux
  copy: src=files/selinux dest=/etc/selinux/config owner=root group=root mode=0644
  notify: reboot vm

- name: add limits for hbase and hdfs users
  copy: src=files/hadoop_limits.conf dest=/etc/security/limits.d/hadoop_limits.conf owner=root group=root mode=0644
  notify: reboot vm

- block:
  - name: disable transparent hugepage for next reboot
    copy: src=files/rc.local dest=/etc/rc.d/rc.local owner=root group=root mode=755
    register: transparent_hugepage

  - name: disable transparent hugepage
    script: files/disable_transparent_hugepage.sh
    when: transparent_hugepage.changed

  - name: start ntpd
    systemd: name=ntpd state=started enabled=yes  

  - name: start nscd
    systemd: name=nscd state=started enabled=yes
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

- block:

  - name: start ntpd
    service: name=ntpd state=started enabled=yes
  
  - name: start nscd
    service: name=nscd state=started enabled=yes
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '6'

- name: set swappiness after reboot
  lineinfile: dest=/etc/sysctl.conf state=present line="vm.swappiness=10"
  notify: reboot vm

- name: deploy krb.conf
  template: src=templates/krb5.conf.j2 dest=/etc/krb5.conf

