---
# handlers file for hadoop-bootstrap

- name: reboot vm
  shell: shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  notify: wait for server

- name: wait for server
  local_action: wait_for host={{ ansible_ssh_host | default(inventory_hostname) }} port=22 delay=10 search_regex=OpenSSH
  become: no
